{
    "name": "MpdClient",
    "version": "0.0.34",
    "icon": "fas fa-user-alien",
    "category": "music",
    "author": "glueckself",
    "maintainers": [
        "maxbachmann"
    ],
    "desc": "Control an MPD server",
    "aliceMinVersion": "1.0.0-b3",
    "systemRequirements": [],
    "pipRequirements": [
        "python-mpd2"
    ],
    "conditions": {
        "lang": [
            "en",
            "de"
        ]
    }
}